# Server configuration
server:
  port: ":8080"
  grpc_port: ":50051"

# Logger configuration
logger:
  level: "info"

# Redis configuration
redis:
  addr: "localhost:6379"
  pool_size: 0 # Maximum number of socket connections (0 resolved dynamically)
