# Dev Environment Configuration
server:
  port: ":8080"
  grpc_port: ":50051"
logger:
  level: "debug" # More verbose logging
redis:
  addr: "localhost:6379"
  pool_size: 0

taskmq:
  codec: "binary"
  shutdown_timeout: 30s
  queues:
    - name: "default"
      concurrency: 5
