// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/taskmq/v1/taskmq.proto

package taskmqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskMQService_Enqueue_FullMethodName          = "/taskmq.v1.TaskMQService/Enqueue"
	TaskMQService_EnqueueIn_FullMethodName        = "/taskmq.v1.TaskMQService/EnqueueIn"
	TaskMQService_EnqueueAt_FullMethodName        = "/taskmq.v1.TaskMQService/EnqueueAt"
	TaskMQService_RegisterCron_FullMethodName     = "/taskmq.v1.TaskMQService/RegisterCron"
	TaskMQService_ListDeadLetters_FullMethodName  = "/taskmq.v1.TaskMQService/ListDeadLetters"
	TaskMQService_DeleteDeadLetter_FullMethodName = "/taskmq.v1.TaskMQService/DeleteDeadLetter"
	TaskMQService_RetryDeadLetter_FullMethodName  = "/taskmq.v1.TaskMQService/RetryDeadLetter"
)

// TaskMQServiceClient is the client API for TaskMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskMQService provides APIs for multi-language enqueuing and queue management.
type TaskMQServiceClient interface {
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	EnqueueIn(ctx context.Context, in *EnqueueInRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	EnqueueAt(ctx context.Context, in *EnqueueAtRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	RegisterCron(ctx context.Context, in *RegisterCronRequest, opts ...grpc.CallOption) (*RegisterCronResponse, error)
	ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error)
	DeleteDeadLetter(ctx context.Context, in *DeleteDeadLetterRequest, opts ...grpc.CallOption) (*DeleteDeadLetterResponse, error)
	RetryDeadLetter(ctx context.Context, in *RetryDeadLetterRequest, opts ...grpc.CallOption) (*RetryDeadLetterResponse, error)
}

type taskMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskMQServiceClient(cc grpc.ClientConnInterface) TaskMQServiceClient {
	return &taskMQServiceClient{cc}
}

func (c *taskMQServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, TaskMQService_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) EnqueueIn(ctx context.Context, in *EnqueueInRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, TaskMQService_EnqueueIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) EnqueueAt(ctx context.Context, in *EnqueueAtRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, TaskMQService_EnqueueAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) RegisterCron(ctx context.Context, in *RegisterCronRequest, opts ...grpc.CallOption) (*RegisterCronResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCronResponse)
	err := c.cc.Invoke(ctx, TaskMQService_RegisterCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeadLettersResponse)
	err := c.cc.Invoke(ctx, TaskMQService_ListDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) DeleteDeadLetter(ctx context.Context, in *DeleteDeadLetterRequest, opts ...grpc.CallOption) (*DeleteDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeadLetterResponse)
	err := c.cc.Invoke(ctx, TaskMQService_DeleteDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskMQServiceClient) RetryDeadLetter(ctx context.Context, in *RetryDeadLetterRequest, opts ...grpc.CallOption) (*RetryDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryDeadLetterResponse)
	err := c.cc.Invoke(ctx, TaskMQService_RetryDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskMQServiceServer is the server API for TaskMQService service.
// All implementations must embed UnimplementedTaskMQServiceServer
// for forward compatibility.
//
// TaskMQService provides APIs for multi-language enqueuing and queue management.
type TaskMQServiceServer interface {
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	EnqueueIn(context.Context, *EnqueueInRequest) (*EnqueueResponse, error)
	EnqueueAt(context.Context, *EnqueueAtRequest) (*EnqueueResponse, error)
	RegisterCron(context.Context, *RegisterCronRequest) (*RegisterCronResponse, error)
	ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error)
	DeleteDeadLetter(context.Context, *DeleteDeadLetterRequest) (*DeleteDeadLetterResponse, error)
	RetryDeadLetter(context.Context, *RetryDeadLetterRequest) (*RetryDeadLetterResponse, error)
	mustEmbedUnimplementedTaskMQServiceServer()
}

// UnimplementedTaskMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskMQServiceServer struct{}

func (UnimplementedTaskMQServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedTaskMQServiceServer) EnqueueIn(context.Context, *EnqueueInRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueIn not implemented")
}
func (UnimplementedTaskMQServiceServer) EnqueueAt(context.Context, *EnqueueAtRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueAt not implemented")
}
func (UnimplementedTaskMQServiceServer) RegisterCron(context.Context, *RegisterCronRequest) (*RegisterCronResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCron not implemented")
}
func (UnimplementedTaskMQServiceServer) ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeadLetters not implemented")
}
func (UnimplementedTaskMQServiceServer) DeleteDeadLetter(context.Context, *DeleteDeadLetterRequest) (*DeleteDeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDeadLetter not implemented")
}
func (UnimplementedTaskMQServiceServer) RetryDeadLetter(context.Context, *RetryDeadLetterRequest) (*RetryDeadLetterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryDeadLetter not implemented")
}
func (UnimplementedTaskMQServiceServer) mustEmbedUnimplementedTaskMQServiceServer() {}
func (UnimplementedTaskMQServiceServer) testEmbeddedByValue()                       {}

// UnsafeTaskMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskMQServiceServer will
// result in compilation errors.
type UnsafeTaskMQServiceServer interface {
	mustEmbedUnimplementedTaskMQServiceServer()
}

func RegisterTaskMQServiceServer(s grpc.ServiceRegistrar, srv TaskMQServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskMQService_ServiceDesc, srv)
}

func _TaskMQService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_EnqueueIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).EnqueueIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_EnqueueIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).EnqueueIn(ctx, req.(*EnqueueInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_EnqueueAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).EnqueueAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_EnqueueAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).EnqueueAt(ctx, req.(*EnqueueAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_RegisterCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCronRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).RegisterCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_RegisterCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).RegisterCron(ctx, req.(*RegisterCronRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_ListDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).ListDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_ListDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).ListDeadLetters(ctx, req.(*ListDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_DeleteDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).DeleteDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_DeleteDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).DeleteDeadLetter(ctx, req.(*DeleteDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskMQService_RetryDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskMQServiceServer).RetryDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskMQService_RetryDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskMQServiceServer).RetryDeadLetter(ctx, req.(*RetryDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskMQService_ServiceDesc is the grpc.ServiceDesc for TaskMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskmq.v1.TaskMQService",
	HandlerType: (*TaskMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _TaskMQService_Enqueue_Handler,
		},
		{
			MethodName: "EnqueueIn",
			Handler:    _TaskMQService_EnqueueIn_Handler,
		},
		{
			MethodName: "EnqueueAt",
			Handler:    _TaskMQService_EnqueueAt_Handler,
		},
		{
			MethodName: "RegisterCron",
			Handler:    _TaskMQService_RegisterCron_Handler,
		},
		{
			MethodName: "ListDeadLetters",
			Handler:    _TaskMQService_ListDeadLetters_Handler,
		},
		{
			MethodName: "DeleteDeadLetter",
			Handler:    _TaskMQService_DeleteDeadLetter_Handler,
		},
		{
			MethodName: "RetryDeadLetter",
			Handler:    _TaskMQService_RetryDeadLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/taskmq/v1/taskmq.proto",
}
