// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/taskmq/v1/taskmq.proto

package taskmqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,5,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	UniqueKey     string                 `protobuf:"bytes,7,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	UniqueTtlMs   int64                  `protobuf:"varint,8,opt,name=unique_ttl_ms,json=uniqueTtlMs,proto3" json:"unique_ttl_ms,omitempty"`
	CronSpec      string                 `protobuf:"bytes,9,opt,name=cron_spec,json=cronSpec,proto3" json:"cron_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *Task) GetUniqueTtlMs() int64 {
	if x != nil {
		return x.UniqueTtlMs
	}
	return 0
}

func (x *Task) GetCronSpec() string {
	if x != nil {
		return x.CronSpec
	}
	return ""
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type EnqueueInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	DelayMs       int64                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueInRequest) Reset() {
	*x = EnqueueInRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueInRequest) ProtoMessage() {}

func (x *EnqueueInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueInRequest.ProtoReflect.Descriptor instead.
func (*EnqueueInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueInRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *EnqueueInRequest) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type EnqueueAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueAtRequest) Reset() {
	*x = EnqueueAtRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueAtRequest) ProtoMessage() {}

func (x *EnqueueAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueAtRequest.ProtoReflect.Descriptor instead.
func (*EnqueueAtRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueueAtRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *EnqueueAtRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type RegisterCronRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	CronSpec      string                 `protobuf:"bytes,2,opt,name=cron_spec,json=cronSpec,proto3" json:"cron_spec,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCronRequest) Reset() {
	*x = RegisterCronRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCronRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCronRequest) ProtoMessage() {}

func (x *RegisterCronRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCronRequest.ProtoReflect.Descriptor instead.
func (*RegisterCronRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterCronRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *RegisterCronRequest) GetCronSpec() string {
	if x != nil {
		return x.CronSpec
	}
	return ""
}

func (x *RegisterCronRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type RegisterCronResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCronResponse) Reset() {
	*x = RegisterCronResponse{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCronResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCronResponse) ProtoMessage() {}

func (x *RegisterCronResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCronResponse.ProtoReflect.Descriptor instead.
func (*RegisterCronResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterCronResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListDeadLettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersRequest) Reset() {
	*x = ListDeadLettersRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersRequest) ProtoMessage() {}

func (x *ListDeadLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersRequest.ProtoReflect.Descriptor instead.
func (*ListDeadLettersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeadLettersRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListDeadLettersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDeadLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersResponse) Reset() {
	*x = ListDeadLettersResponse{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersResponse) ProtoMessage() {}

func (x *ListDeadLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersResponse.ProtoReflect.Descriptor instead.
func (*ListDeadLettersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{8}
}

func (x *ListDeadLettersResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DeleteDeadLetterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeadLetterRequest) Reset() {
	*x = DeleteDeadLetterRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeadLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeadLetterRequest) ProtoMessage() {}

func (x *DeleteDeadLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeadLetterRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeadLetterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDeadLetterRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DeleteDeadLetterRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteDeadLetterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeadLetterResponse) Reset() {
	*x = DeleteDeadLetterResponse{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeadLetterResponse) ProtoMessage() {}

func (x *DeleteDeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeadLetterResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDeadLetterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetryDeadLetterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadLetterRequest) Reset() {
	*x = RetryDeadLetterRequest{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadLetterRequest) ProtoMessage() {}

func (x *RetryDeadLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadLetterRequest.ProtoReflect.Descriptor instead.
func (*RetryDeadLetterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{11}
}

func (x *RetryDeadLetterRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *RetryDeadLetterRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RetryDeadLetterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDeadLetterResponse) Reset() {
	*x = RetryDeadLetterResponse{}
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDeadLetterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDeadLetterResponse) ProtoMessage() {}

func (x *RetryDeadLetterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmq_v1_taskmq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDeadLetterResponse.ProtoReflect.Descriptor instead.
func (*RetryDeadLetterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP(), []int{12}
}

func (x *RetryDeadLetterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_taskmq_v1_taskmq_proto protoreflect.FileDescriptor

const file_api_proto_taskmq_v1_taskmq_proto_rawDesc = "" +
	"\n" +
	" api/proto/taskmq/v1/taskmq.proto\x12\ttaskmq.v1\"\xf6\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1b\n" +
	"\tmax_retry\x18\x05 \x01(\x05R\bmaxRetry\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12\x1d\n" +
	"\n" +
	"unique_key\x18\a \x01(\tR\tuniqueKey\x12\"\n" +
	"\runique_ttl_ms\x18\b \x01(\x03R\vuniqueTtlMs\x12\x1b\n" +
	"\tcron_spec\x18\t \x01(\tR\bcronSpec\"5\n" +
	"\x0eEnqueueRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.taskmq.v1.TaskR\x04task\"*\n" +
	"\x0fEnqueueResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"R\n" +
	"\x10EnqueueInRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.taskmq.v1.TaskR\x04task\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x03R\adelayMs\"Z\n" +
	"\x10EnqueueAtRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.taskmq.v1.TaskR\x04task\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"r\n" +
	"\x13RegisterCronRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x1b\n" +
	"\tcron_spec\x18\x02 \x01(\tR\bcronSpec\x12#\n" +
	"\x04task\x18\x03 \x01(\v2\x0f.taskmq.v1.TaskR\x04task\"0\n" +
	"\x14RegisterCronResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x16ListDeadLettersRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x17ListDeadLettersResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.taskmq.v1.TaskR\x05tasks\"H\n" +
	"\x17DeleteDeadLetterRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"4\n" +
	"\x18DeleteDeadLetterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x16RetryDeadLetterRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"3\n" +
	"\x17RetryDeadLetterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbf\x04\n" +
	"\rTaskMQService\x12@\n" +
	"\aEnqueue\x12\x19.taskmq.v1.EnqueueRequest\x1a\x1a.taskmq.v1.EnqueueResponse\x12D\n" +
	"\tEnqueueIn\x12\x1b.taskmq.v1.EnqueueInRequest\x1a\x1a.taskmq.v1.EnqueueResponse\x12D\n" +
	"\tEnqueueAt\x12\x1b.taskmq.v1.EnqueueAtRequest\x1a\x1a.taskmq.v1.EnqueueResponse\x12O\n" +
	"\fRegisterCron\x12\x1e.taskmq.v1.RegisterCronRequest\x1a\x1f.taskmq.v1.RegisterCronResponse\x12X\n" +
	"\x0fListDeadLetters\x12!.taskmq.v1.ListDeadLettersRequest\x1a\".taskmq.v1.ListDeadLettersResponse\x12[\n" +
	"\x10DeleteDeadLetter\x12\".taskmq.v1.DeleteDeadLetterRequest\x1a#.taskmq.v1.DeleteDeadLetterResponse\x12X\n" +
	"\x0fRetryDeadLetter\x12!.taskmq.v1.RetryDeadLetterRequest\x1a\".taskmq.v1.RetryDeadLetterResponseB6Z4github.com/twn39/taskmq/api/proto/taskmq/v1;taskmqv1b\x06proto3"

var (
	file_api_proto_taskmq_v1_taskmq_proto_rawDescOnce sync.Once
	file_api_proto_taskmq_v1_taskmq_proto_rawDescData []byte
)

func file_api_proto_taskmq_v1_taskmq_proto_rawDescGZIP() []byte {
	file_api_proto_taskmq_v1_taskmq_proto_rawDescOnce.Do(func() {
		file_api_proto_taskmq_v1_taskmq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_taskmq_v1_taskmq_proto_rawDesc), len(file_api_proto_taskmq_v1_taskmq_proto_rawDesc)))
	})
	return file_api_proto_taskmq_v1_taskmq_proto_rawDescData
}

var file_api_proto_taskmq_v1_taskmq_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_taskmq_v1_taskmq_proto_goTypes = []any{
	(*Task)(nil),                     // 0: taskmq.v1.Task
	(*EnqueueRequest)(nil),           // 1: taskmq.v1.EnqueueRequest
	(*EnqueueResponse)(nil),          // 2: taskmq.v1.EnqueueResponse
	(*EnqueueInRequest)(nil),         // 3: taskmq.v1.EnqueueInRequest
	(*EnqueueAtRequest)(nil),         // 4: taskmq.v1.EnqueueAtRequest
	(*RegisterCronRequest)(nil),      // 5: taskmq.v1.RegisterCronRequest
	(*RegisterCronResponse)(nil),     // 6: taskmq.v1.RegisterCronResponse
	(*ListDeadLettersRequest)(nil),   // 7: taskmq.v1.ListDeadLettersRequest
	(*ListDeadLettersResponse)(nil),  // 8: taskmq.v1.ListDeadLettersResponse
	(*DeleteDeadLetterRequest)(nil),  // 9: taskmq.v1.DeleteDeadLetterRequest
	(*DeleteDeadLetterResponse)(nil), // 10: taskmq.v1.DeleteDeadLetterResponse
	(*RetryDeadLetterRequest)(nil),   // 11: taskmq.v1.RetryDeadLetterRequest
	(*RetryDeadLetterResponse)(nil),  // 12: taskmq.v1.RetryDeadLetterResponse
}
var file_api_proto_taskmq_v1_taskmq_proto_depIdxs = []int32{
	0,  // 0: taskmq.v1.EnqueueRequest.task:type_name -> taskmq.v1.Task
	0,  // 1: taskmq.v1.EnqueueInRequest.task:type_name -> taskmq.v1.Task
	0,  // 2: taskmq.v1.EnqueueAtRequest.task:type_name -> taskmq.v1.Task
	0,  // 3: taskmq.v1.RegisterCronRequest.task:type_name -> taskmq.v1.Task
	0,  // 4: taskmq.v1.ListDeadLettersResponse.tasks:type_name -> taskmq.v1.Task
	1,  // 5: taskmq.v1.TaskMQService.Enqueue:input_type -> taskmq.v1.EnqueueRequest
	3,  // 6: taskmq.v1.TaskMQService.EnqueueIn:input_type -> taskmq.v1.EnqueueInRequest
	4,  // 7: taskmq.v1.TaskMQService.EnqueueAt:input_type -> taskmq.v1.EnqueueAtRequest
	5,  // 8: taskmq.v1.TaskMQService.RegisterCron:input_type -> taskmq.v1.RegisterCronRequest
	7,  // 9: taskmq.v1.TaskMQService.ListDeadLetters:input_type -> taskmq.v1.ListDeadLettersRequest
	9,  // 10: taskmq.v1.TaskMQService.DeleteDeadLetter:input_type -> taskmq.v1.DeleteDeadLetterRequest
	11, // 11: taskmq.v1.TaskMQService.RetryDeadLetter:input_type -> taskmq.v1.RetryDeadLetterRequest
	2,  // 12: taskmq.v1.TaskMQService.Enqueue:output_type -> taskmq.v1.EnqueueResponse
	2,  // 13: taskmq.v1.TaskMQService.EnqueueIn:output_type -> taskmq.v1.EnqueueResponse
	2,  // 14: taskmq.v1.TaskMQService.EnqueueAt:output_type -> taskmq.v1.EnqueueResponse
	6,  // 15: taskmq.v1.TaskMQService.RegisterCron:output_type -> taskmq.v1.RegisterCronResponse
	8,  // 16: taskmq.v1.TaskMQService.ListDeadLetters:output_type -> taskmq.v1.ListDeadLettersResponse
	10, // 17: taskmq.v1.TaskMQService.DeleteDeadLetter:output_type -> taskmq.v1.DeleteDeadLetterResponse
	12, // 18: taskmq.v1.TaskMQService.RetryDeadLetter:output_type -> taskmq.v1.RetryDeadLetterResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_taskmq_v1_taskmq_proto_init() }
func file_api_proto_taskmq_v1_taskmq_proto_init() {
	if File_api_proto_taskmq_v1_taskmq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_taskmq_v1_taskmq_proto_rawDesc), len(file_api_proto_taskmq_v1_taskmq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_taskmq_v1_taskmq_proto_goTypes,
		DependencyIndexes: file_api_proto_taskmq_v1_taskmq_proto_depIdxs,
		MessageInfos:      file_api_proto_taskmq_v1_taskmq_proto_msgTypes,
	}.Build()
	File_api_proto_taskmq_v1_taskmq_proto = out.File
	file_api_proto_taskmq_v1_taskmq_proto_goTypes = nil
	file_api_proto_taskmq_v1_taskmq_proto_depIdxs = nil
}
